name: CD - DAST (OWASP ZAP)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Docker Baseline
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://juice-shop.herokuapp.com -g gen.conf -r zap_report.html -J zap_report.json

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap_report.html
            zap_report.json
